language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
    - "$HOME/.npm"
install:
  - npm install
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: dist
  fqdn: hodl.watch
  on:
    branch: master